### ISSUE TITLE
 error when no compiled _zope_security_checker.c is available and ZOPE_WATCH_CHECKERS is set

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.security#8]
In https://bugs.launchpad.net/zope.security/+bug/599744, @agroszer reported:

> This happened when I tried to debug why security is not working.  I've set `ZOPE_WATCH_CHECKERS`, and killed `_zope_security_checker.so`. On Zope started the following exception appeared.  The problem is that `zope.security.checker.Checker` is redefined when `ZOPE_WATCH_CHECKERS` is defined **after** `_defaultChecker = Checker({})`

``` python
  File "/home/adi/.buildout/eggs/zope.configuration-3.7.2-py2.5.egg/zope/configuration/config.py", line 200, in resolve
    return __import__(mname+'.'+oname, *_import_chickens)
  File "/home/adi/.buildout/eggs/zope.app.pagetemplate-3.11.0-py2.5.egg/zope/app/pagetemplate/__init__.py", line 20, in <module>
    from zope.browserpage import ViewPageTemplateFile
  File "/home/adi/.buildout/eggs/zope.browserpage-3.12.2-py2.5.egg/zope/browserpage/__init__.py", line 1, in <module>
    from zope.browserpage.viewpagetemplatefile import ViewPageTemplateFile
  File "/home/adi/.buildout/eggs/zope.browserpage-3.12.2-py2.5.egg/zope/browserpage/viewpagetemplatefile.py", line 22, in <module>
    from zope.pagetemplate.engine import TrustedAppPT
  File "/home/adi/.buildout/eggs/zope.pagetemplate-3.5.1-py2.5.egg/zope/pagetemplate/engine.py", line 32, in <module>
    from zope.security.untrustedpython.builtins import SafeBuiltins
  File "/home/adi/.buildout/eggs/zope.security-3.7.3-py2.5-linux-i686.egg/zope/security/untrustedpython/builtins.py", line 126, in <module>
    SafeBuiltins = ImmutableModule(**SafeBuiltins())
  File "/home/adi/.buildout/eggs/zope.security-3.7.3-py2.5-linux-i686.egg/zope/security/untrustedpython/builtins.py", line 76, in SafeBuiltins
    value = ProxyFactory(value)
  File "/home/adi/.buildout/eggs/zope.security-3.7.3-py2.5-linux-i686.egg/zope/security/checker.py", line 85, in ProxyFactory
    checker = selectChecker(object)
  File "/home/adi/.buildout/eggs/zope.security-3.7.3-py2.5-linux-i686.egg/zope/security/checker.py", line 380, in selectChecker
    checker = checker(object)
ZopeXMLConfigurationError: File "/home/adi/refline/packages/trunk/pesoftp/src/pesoftp/ftesting.zcml", line 9.2-9.55
    ZopeXMLConfigurationError: File "/home/adi/refline/packages/trunk/pesoftp/src/pesoftp/application.zcml", line 25.2-25.62
    TypeError: 'Checker' object is not callable
```

@tseaver followed up:

> Hmm, I don't know how to reproduce this one: can we come up with a unit test which relies only on zope.security?

**Comment by jamadden** [comment]
With #34, this is now easily reproducible at runtime:
```shell
$ PURE_PYTHON=1 ZOPE_WATCH_CHECKERS=1 zope-testrunner --test-path=src
...
Error in test testMultipleInterface (zope.security.tests.test_zcml_functest.TestRequireDirective)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 320, in run
    self.setUp()
  File "//zope.security/src/zope/security/tests/test_zcml_functest.py", line 379, in setUp
    self.assertState()
  File "/zope.security/src/zope/security/tests/test_zcml_functest.py", line 395, in assertState
    checker = selectChecker(module.test_instance)
  File "//zope.security/src/zope/security/checker.py", line 397, in selectCheckerPy
    checker = checker(object)
TypeError: 'CheckerPy' object is not callable
...

  Ran 664 tests with 0 failures, 47 errors, 152 skipped in 0.320 seconds.
```

**Comment by jamadden** [comment]
And there's another error that also repeats a lot:
```shell
Error in test test_check_lhs_forbidden_rhs_forbidden (zope.security.tests.test_checker.TestCombinedChecker)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "//zope.security/src/zope/security/tests/test_checker.py", line 1225, in test_check_lhs_forbidden_rhs_forbidden
    combined = self._makeOne(lhs, rhs)
  File "//zope.security/src/zope/security/tests/test_checker.py", line 1130, in _makeOne
    return self._getTargetClass()(checker1, checker2)
  File "//zope.security/src/zope/security/checker.py", line 481, in __init__
    checker1.set_permissions)
TypeError: unbound method __init__() must be called with Checker instance as first argument (got CombinedChecker instance instead)
```

**Comment by jamadden** [comment]
The first issue is that `selectCheckerPy` does `while not instance(checker, Checker)`, and if `checker` is `_defaultChecker` which has already been defined, that will never be true, to it keeps trying to call it until it gets a TypeError. This is fairly easily solved by re-defining `_defaultChecker` in the branch that redefines the `Checker` class if the C extension is not available. (Alternatively, `if checker is _defaultChecker` could be added to the `while` loop.)

**Comment by jamadden** [comment]
The second case is also easy, we just need to tweak the MRO, like so (this has both fixes):
```python
if WATCH_CHECKERS: #pragma NO COVER
    class WatchingChecker(CheckerLoggingMixin, Checker):
        verbosity = WATCH_CHECKERS
    class WatchingCombinedChecker(CombinedChecker, WatchingChecker):
        verbosity = WATCH_CHECKERS

    Checker = WatchingChecker
    CombinedChecker = WatchingCombinedChecker

    if not _c_available:
        _defaultChecker.__class__ = Checker
```

(The unique class names made debugging this much easier. In fact, maybe those Watching classes should always be defined for ease of *localized* debuging?)

Now, all tests pass with ZOPE_WATCH_CHECKERS set, with both PURE_PYTHON set and unset.

Those should be added to the .travis.yml matrix after #34 or a variant is merged.
