### ISSUE TITLE
Python 3.12 on GHA compatibility issue

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/zope.security#99]
The exception shown below is thrown on Python 3.12 on the macOS and Ubuntu GitHub Actions runners. Please note:

- I cannot reproduce it on a local Linux/x86_64 (Rocky Linux 9)
- I cannot reproduce it on a local macOS/arm64
- I cannot reproduce it on a local macOS/x86_64 with the same `universal2`-Architecture Python used by the GHA runner
- The `zope.proxy` test suite runs fine on Python 3.12 on GHA, indicating `zope.proxy` itself is not the culprit

```
Error in test test___getattr___w_checker_unauthorized (zope.security.tests.test_proxy.ProxyPyTests.test___getattr___w_checker_unauthorized)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/home/runner/work/zope.security/zope.security/src/zope/security/tests/test_proxy.py", line 55, in test___getattr___w_checker_unauthorized
    self.assertRaises(Unauthorized, getattr, proxy, 'bar')
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/unittest/case.py", line 778, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/unittest/case.py", line 238, in handle
    callable_obj(*args, **kwargs)
  File "/home/runner/work/zope.security/zope.security/src/zope/security/proxy.py", line 156, in __getattr__
    wrapped = super().__getattribute__('_wrapped')
SystemError: <class 'super'> returned a result with an exception set
```

**Comment by icemac** [comment]
Could it be that https://github.com/zopefoundation/zope.proxy/issues/43 is the reason behind this problem? Maybe it is just not triggered by the zope.proxy tests.
See https://github.com/python/cpython/issues/73734 for details about the replacement for the deprecated function.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2023-4-24 00:56 -0700:
>Could it be that https://github.com/zopefoundation/zope.proxy/issues/43 is the reason behind this problem? Maybe it is just not triggered by the zope.proxy tests.
>See https://github.com/python/cpython/issues/73734 for details about the replacement for the deprecated function.

I do not think so:
Such a problem should show up also for local tests, not only
for the GHA tests (unless the executed tests would be different).

I think something is wrong with the pregenerated wheel.
Do you know a way to download this wheel to a local machine?
Then, one could unpack the wheel to emulate the GHA test
on the local machine -- hopefully reproducing the problem.

**Comment by dataflake** [comment]
Click on the Actions tab at the top, select a test run and then scroll down the right-side pane. The wheels are listed underneath the warning and error messages and can be downloaded from there.

**Comment by icemac** [comment]
Using Python 3.12b2 the problems vanished, see #100.
